CorpGlory/grafana-datasource-kit

- jest.config.js
- package.json
- spec/basic.jest.ts
- spec/setup_tests.ts
- testfile.ts
- tsconfig.jest.json
- tsconfig.json
Add jest to project.
Add basic test to see if works.
> add ject to project

- package.json
- src/grafana_service.ts
Closes https://github.com/CorpGlory/grafana-datasource-kit/issues/11
- change queryByMetric return type
- proper url compose
- fix deps
> Unexpected return type in queryByMetric #11

- spec/targets.jest.ts
- added tests for InfluxDB and Graphite
> add simple tests

- src/metrics/graphite_metric.ts
- src/metrics/metrics_factory.ts
checked if resonce.data has zero length
Fixes https://github.com/CorpGlory/grafana-datasource-kit/issues/21
> fix empty responce case

- src/grafana_service.ts
- src/metrics/prometheus_metric.ts
- implementation of prometheus metric
> add metrics parser

- src/metrics/graphite_metric.ts
- src/metrics/influxdb_metric.ts
- src/metrics/prometheus_metric.ts
Return empty dict if datasource return undefined or zero length response
Fixes https://github.com/CorpGlory/grafana-datasource-kit/issues/23
> Fixed return value if data undefined in responce

- src/metrics/prometheus_metric.ts
return matrix like follow:
timestamp, metric1:labels1, ....
1234,val1,val2,.....
....
....
Fixes https://github.com/CorpGlory/grafana-datasource-kit/issues/26
> Prometheus one metric instead of multiple #26

- src/grafana_service.ts
- src/metrics/graphite_metric.ts
- src/metrics/influxdb_metric.ts
- src/metrics/metric.ts
- src/metrics/metrics_factory.ts
- src/metrics/postgres_metric.ts
- src/metrics/prometheus_metric.ts
- Added support of Postgres datasource
- Small refactoring of grafana_service.ts
> Postgres datasource

- spec/postgres.jest.ts
- spec/setup_tests.ts
- spec/utils.jest.ts
- src/metrics/utils.ts
processes only limits and offsets thats not in parentheses
fixes #38
> Fix postgres limit offset processing #38

- .travis.yml
- package.json
> add npm publishing on tags

- spec/graphite.jest.ts
- src/metrics/graphite_metric.ts
> Correct processing of time clause and maxDataPoints params

- spec/elasticsearch.jest.ts
- src/metrics/elasticsearch_metric.ts
- src/metrics/graphite_metric.ts
- src/metrics/metrics_factory.ts
> Elastic datasource #4

- spec/elasticsearch.jest.ts
- src/metrics/elasticsearch_metric.ts
- size 0 return all documents
- elasticsearch does not support paging for aggregations
fixes #49
> Fix elasticsearch scrolling #49

- src/grafana_service.ts
Fixes #52 
Support grafana at sub-url (e.g. `http://localhost:3000/grafana`)
> Relative path error #52

- src/grafana_service.ts
- src/index.ts
- src/metrics/elasticsearch_metric.ts
> Check if there is request result #57

- src/grafana_service.ts
- src/index.ts
- src/metrics/elasticsearch_metric.ts
> More info in webhooks hastic/hastic-server#382

- src/grafana_service.ts
Closes #61 
- log all errors to console
- response headers in logs
- improved readability of datasource URL
> More info about datasource error #61

- src/metrics/elasticsearch_metric.ts
fixes #72 
- added missed newline
> Elasticsearch: Request failed with status code 400 #72

- src/grafana_service.ts
> Data kit error status code 400 #76

- src/metrics/elasticsearch_metric.ts
fix #80 
- use time field from `datasource` structure instead of using `@timestamp`
> Cannot set property 'gte' of undefined #80

- package.json
- Error: status code 400 #76
- Cannot set property 'gte' of undefined #80
> Bump version to 0.1.17

- .gitignore
- package-lock.json
datasource-kit can't be built without `package-lock.json`. Some dependency update breaks the build
> do not gitignore package-lock.json
